[package]
name = "brave-wallet-cxx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"
ed25519-dalek-bip32 = "0.2.0"
curve25519-dalek = "3.2.0"

[lib]
name = "brave_wallet_cxx"
path = "lib.rs"
crate-type = ["rlib"]
