language: node_js
node_js:
  - "11.10.1"

dist: trusty
sudo: required

branches:
  only:
    - master
    - /\d+\.\d+\.x/

cache:
  directories:
    - $HOME/.npm
    - node_modules

env:
  - TEST_SUITE=lint
  - TEST_SUITE=test-security
  - TEST_SUITE=test-unit
  - TEST_SUITE=pep8

before_install:
  - npm i -g npm
  - npm --version
  - sudo pip install --upgrade pip
  - sudo pip install pycodestyle

install:
  - npm i

script:
  - npm run $TEST_SUITE



