[package]
name = "brave_client_attestation"
version = "0.1.0"
authors = ["gpestana <gpestana@brave.com>"]
edition = "2018"

[dependencies]
curve25519-dalek = { version = "2.0.0", default-features = false, features = ["serde"] } 
elgamal_ristretto = { git = "https://github.com/iquerejeta/elgamal" }
rand_core = { version = "0.5.1", default-features = false }
repsys_crypto = { path = "./repsys-crypto" }
bincode = "1"
sha2 = "0.8.0" 

