# Copyright (c) 2025 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

[[substitution]]
description = 'Remove final keyword from DraggingTabsSession to allow subclassing'
pattern = 'class DraggingTabsSession final {'
replace = 'class DraggingTabsSession {'

[[substitution]]
description = 'Remove final keyword from DraggingTabsSession to allow subclassing'
pattern = '~DraggingTabsSession();'
replace = 'virtual ~DraggingTabsSession();'
  