[package]
name = "skus-cxx"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"
async-trait = "0.1.61"
futures = "0.3.19"
libc = { version = "0.2" }
skus = { path = "../lib" }
serde_json = "1.0"
tracing-subscriber = "0.2"
tracing = "0.1"

[lib]
name = "skus_cxx"
crate-type = ["rlib"]
