[package]
name = "speedreader-ffi"
version = "0.1.0"
authors = ["Andrius Aucinas <aaucinas@brave.com>"]
edition = "2018"

[dependencies]
speedreader = { path = "../lib/" }
libc = "0.2.107"
[patch.crates-io]
cssparser = { git = 'https://github.com/AndriusA/rust-cssparser', branch = "glibc" }

[profile.release]
panic = "abort"

[lib]
name = "speedreader_ffi"
path = "lib.rs"
crate-type = ["rlib"]
