[package]
authors = ["eV <ev@7pr.xyz>"]
name = "challenge-bypass-ristretto-ffi"
version = "1.0.0-pre.4"

[dependencies]
base64 = "0.9.3"
challenge-bypass-ristretto = { version = "1.0.1", features = ["base64"] }
hmac = "0.10"
rand = "0.7"
sha2 = "0.9"

[lib]
crate-type = [
    "rlib",
]
name = "challenge_bypass_ristretto_ffi"
path = "../../vendor/challenge_bypass_ristretto_ffi/src/lib.rs"

[features]
nightly = ["challenge-bypass-ristretto/nightly"]
cbindgen = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
