[package]
name = "brave-news-cxx"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = { version = "1.0", features = [ "alloc", "std" ] }
feed-rs = { git = "https://github.com/feed-rs/feed-rs", rev = "f88f21a65f997499962aacb2f746a82382547160" }
log = "0.4.14"
lazy_static = "1.4.0"
regex = "1.5.5"

[lib]
name = "brave_news_cxx"
path = "lib.rs"
crate-type = ["rlib"]
