[package]
name = "brave-news-cxx"
version = "1.0.0"
edition = "2018"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1"
feed-rs = "1.4.0"
log = "0.4.14"
lazy_static = "1.4.0"
regex = "1.5.5"

[lib]
name = "brave_news_cxx"
path = "lib.rs"
crate-type = ["rlib"]
