# The language to output bindings in
language = "C"
include_guard = "BRAVE_COMPONENTS_ADBLOCK_RUST_FFI_SRC_LIB_H_"

header = """
/* Copyright (c) 2019 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */"""
line_length = 80

[parse]
# Whether to parse dependent crates and include their types in the generated
# bindings
parse_deps = true
# A black list of crate names that are not allowed to be parsed
include = ["adblock"]

[parse.expand]
# A list of crate names that should be run through `cargo expand` before
# parsing to expand any macros
# crates = ["adblock-ffi"]
crates = []
all_features = false
default_features = false
features = ["cbindgen"]

[export]
# A prefix to add before the name of every item
prefix = "C_"

[defines]
"feature = ios" = "IS_IOS"
