[package]
name = "skus-sdk"
version = "0.1.0"
authors = ["eV <ev@7pr.xyz>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-trait = "0.1.41"
skus = { path = "../lib", default_features = false, features = ["wasm"] }
futures-util-preview = "0.3.0-alpha.17"
js-sys = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = { version = "0.3", features = ["futures_0_3"] }
web-sys = { version = "0.3", features = ["console", "Headers", "Window", "Request", "RequestInit", "RequestMode", "Response", "Storage", "HtmlDocument", "Location", "Document", "Element", "HtmlIFrameElement", "CssStyleDeclaration", "MessageEvent", "Url", "DomTokenList"] }
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.1.0"
wasm-cookies = "0.1.0"
futures = "0.3"
gloo-timers = { version = "0.2.1", features = ["futures"] }
tracing-subscriber = "0.2"

[features]
wasm = ["skus/wasm"]
