# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

[[substitution]]
description = "Insert custom title check into TabUIHelper::GetTitle."
re_pattern = '^(std::u16string TabUIHelper::GetTitle\(\).*\n)'
replace = '''\1  if (base::FeatureList::IsEnabled(tabs::kBraveRenamingTabs) && custom_title_) {
    return *custom_title_;
  }
'''
re_flags = ['MULTILINE']
