name: Assign labels

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  label:
    name: Assign labels
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

    - name: set ci managed labels (automatically set and unset)
      uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
        configuration-path: .github/synced-labels.yml


    - name: set optional labels
      uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: false
        configuration-path: .github/optional-labels.yml
